### ISSUE TITLE
Store keypair

### ISSUE THREAD

**Issue by grarco** [anoma/trusted-setup-ceremony#11]
Store the generated keypair to file json encoded.
Encrypt this file and add info about the contributions: contribution hash, timestamp, contribution hash file.

**Comment by grarco** [comment]
At the moment, a contributor will write a `contributor.keypair` file. The name of this file is unique, which is good for production use but it limits testing because now it is not possible to spawn multiple contributors locally. This is because after the first contributor has written the file, all the subsequent ones will reuse the same keypair and, therefore, the same public key which is already known by the coordinator which will, eventually, reject it.

It is still possible to test multiple local contributions by deleting the file as soon as it's generated but this makes testing more tedious. We should try to find a way around this.

**Comment by gnosed** [comment]
For the key pair generation, we would like to generate the private key with a 24-word seed phrase. We can use the [BIP39 crate](https://docs.rs/tiny-bip39/latest/bip39/#). From the generated mnemonic, we can obtain the seed bytes that we can then input into the `ed25519` to generate the key pair.

```rust
```
