### ISSUE TITLE
CLI User flow 

### ISSUE THREAD

**Issue by gnosed** [anoma/trusted-setup-ceremony#21]
The CLI needs to ask a couple of questions to the user that will determine the execution flow:

1. Do you want to participate in the incentivised trusted setup?
2. Do you want to take part in the contest?
3. Do you want to contribute on another machine?
4. Do you want to input your own seed of randomness?

Question 1. and 2. are asked when the user runs the CLI. At the end of the ceremony, input data (full name, email, contest_participant) needs to be signed together with the contribution hash, contribution file hash and public key, then sent back to the coordinator.

Question 3. and 4. are asked when the user has acquired the lock and the challenge was saved as a file. If the user wants to contribute on another machine we should have `--offline` flag that will skip the communication steps with the coordinator and go straight to the contribution part.

**Comment by grarco** [comment]
Regarding the seed of randomness (`phase1-coordinator/commands/computation.rs`), there are two cases:

- if the user doesn't want to use his own seed of randomness we are going to ask him for some entropy (random string, arbitrary length)
- if the user uses his own seed of randomness we are asking him to enter the string of 32 bytes

**Comment by grarco** [comment]
Concerning the `--offline` flag: once the user has answered the question there are two cases:

- if the user doesn't want to compute the randomness on a different machine we proceed as usual with the current execution path
- if he wants to there are two different nested cases:
  - case one, he computes the randomness by himself as long as the produced file complies with the expected one, and then copy this file on the connected machine in a specified path that the client will check periodically
  - case two, he computes the 
  -
