### ISSUE TITLE
Compress contribution info

### ISSUE THREAD

**Issue by grarco** [anoma/trusted-setup-ceremony#26]
The endpoint `/contribution_info` returns a json encoding a list of dictionaries which will grow in size quite a bit during the ceremony. We should make sure to compress the response of this endpoint

**Comment by Fraccaman** [comment]
I think we could skip gzip compression in rocket since we are going to serve the content thought AWS CDN (cloudfront). Cloudfront will take care of compressing the response according to the request headers.

**Comment by grarco** [comment]
Great! Then we only need to adjust the `get_contributions_info` request in the `phase1-cli/src/requests.rs` file
